### ISSUE TITLE
Selly API now requires SNI

### ISSUE THREAD

**Issue by shanoor** [revolunet/node-sellsy#4]
A recent change in Sellsy's infrastructure requires API client to support SNI. Right, now the request is being 401 rejected for invalid signature reason

![node-sellsy](https://cloud.githubusercontent.com/assets/17402800/17769787/6a6ce3b6-654b-11e6-9398-913eed6ab3fb.PNG)

I tried to use [node-oauth](https://www.npmjs.com/package/oauth) directly but I get the same error and I can't find a nodejs oauth package supporting SNI out of the box.

**Comment by revolunet** [comment]
Hi, i dont have issues with this as i use node-sellsy as a client to the sellsy API, using an express server, and didnt notice any issue yet.

**Comment by shanoor** [comment]
Interesting. I also tried with Express but the same error occurs. If I remember correctly, it worked fine even after the Sellsy API change. It's an ongoing dev and recently, I had to regen my tokens, since then, it doesn't work. Are you using "old" tokens (generated before the 29/06/2016) by chance?

**Comment by revolunet** [comment]
i still use my initial tokens, didnt had to change anything.
Note : i'm using heroku to host that app

**Comment by shanoor** [comment]
Ok thank you. It seems you are not affected by this SNI requirement when using old tokens, too bad for me and my new tokens. Thank you anyway, I look for a workaround.

**Comment by revolunet** [comment]
ok sorry please report back if you find any useful info :)

**Comment by johnkrovitch** [comment]
Hi.

@shanoor Did you find any info ? I am facing the same issue right now.
